# Generated by Django 6.0.2 on 2026-02-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name="Nom de l'auteur")),
                ('year_born', models.SmallIntegerField(blank=True, null=True, verbose_name='Annee de naissance')),
            ],
            options={
                'verbose_name': 'Auteur',
                'verbose_name_plural': 'Auteurs',
                'ordering': ['author'],
            },
        ),
    ]
