# Generated by Django 6.0.2 on 2026-02-17 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('summary', models.TextField(blank=True, verbose_name='Resume')),
                ('genre', models.CharField(choices=[('roman', 'Roman'), ('policier', 'Policier'), ('sf', 'Science-Fiction'), ('fantasy', 'Fantasy'), ('historique', 'Historique'), ('biographie', 'Biographie'), ('essai', 'Essai'), ('poesie', 'Poesie'), ('theatre', 'Theatre'), ('jeunesse', 'Jeunesse'), ('bd', 'Bande dessinee'), ('autre', 'Autre')], default='roman', max_length=20, verbose_name='Genre')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='catalogue.author', verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
                'ordering': ['title'],
            },
        ),
    ]
