# Generated by Django 6.0.2 on 2026-02-28 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Raison sociale')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='Ville')),
                ('state', models.CharField(blank=True, max_length=10, verbose_name='Region')),
                ('zip_code', models.CharField(blank=True, max_length=15, verbose_name='Code postal')),
                ('telephone', models.CharField(blank=True, max_length=15, verbose_name='Telephone')),
                ('fax', models.CharField(blank=True, max_length=15, verbose_name='Fax')),
                ('comments', models.TextField(blank=True, verbose_name='Commentaires')),
            ],
            options={
                'verbose_name': 'Editeur',
                'verbose_name_plural': 'Editeurs',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='catalogue.publisher', verbose_name='Editeur'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reserved', models.DateTimeField(auto_now_add=True, verbose_name='Date de reservation')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalogue.book', verbose_name='Livre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-date_reserved'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
